passionProject/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace passionProject.Models
{
    public class Actor
    {
        //actor property
        [Key]
        public int ActorID { get; set; }

        [Required, StringLength(150), Display(Name = "FirstName")]
        public string ActorFName { get; set; }

        [Required, StringLength(150), Display(Name = "LastName")]
        public string ActorLName { get; set; }
         // one actor have many movies
        public virtual ICollection<Movies> Movie { get; set; }
    }



}

passionProject/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using passionProject.Models;
using passionProject.Models.ViewModels;
using System.Diagnostics;

namespace passionProject.Controllers
{
    public class ActorController : Controller
    {
        private ActorCMSContext db = new ActorCMSContext();
        
        // GET: Actor
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            
            IEnumerable <Actor> actors = db.Actors.ToList();
            return View(actors);
        }
        //get : create actor
        public ActionResult create()
        {
            

            ActorEdit actoreditview = new ActorEdit();
            return View(actoreditview);
        }


        [HttpPost]
        public ActionResult create(string ActorFName_New, string ActorLName_New)
        {
            // Basic query   
            string query = "insert into actors (ActorFName,ActorLName ) values (@firstname, @lastname)";
            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@firstname", ActorFName_New);
            myparams[1] = new SqlParameter("@bio", ActorLName_New);
            
           
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }



        public ActionResult Edit(int id)
        {
            //For edit we need a list of actors 
            

            ActorEdit actoreditview = new ActorEdit();
            
            actoreditview.actor = db.Actors.Find(id);

            return View(actoreditview);
        }
        [HttpPost]
        public ActionResult Edit(int id, string ActorFName, string ActorLName)
        {
            //If the ID doesn't exist or the actor doesn't exist
            if ((id == null) || (db.Actors.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "update actors set ActorFName=@firstname, ActorLName=@lastname where actorid=@id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@firstname", ActorFName);
            myparams[1] = new SqlParameter("@lastname", ActorLName);
            myparams[3] = new SqlParameter("@id", id);
            
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Show/" + id);
        }
        public ActionResult Show(int? id)
        {
            //If the id doesn't exist or the actor doesn't exist
            if ((id == null) || (db.Actors.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "select * from actors where actorid=@id";
            
            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@id", id);

            
            Actor myactor = db.Actors.SqlQuery(query, myparams).FirstOrDefault();

            return View(myactor);
        }
        public ActionResult Delete(int? id)
        {
            if ((id == null) || (db.Actors.Find(id) == null))
            {
                return HttpNotFound();

            }
           // delete associated movies
           string query = "delete from Movies where actor_ActorID=@id";
           SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);

            // delete actor
            query = "delete from Actors where actorsid=@id";
            param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");
        }



        
    }
}

passionProject/Views/Actor/Edit.cshtml
@model passionProject.Models.ViewModels.ActorEdit
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Actor @Model.actor.ActorFName</h2>

<form method="POST" action="/Actor/Edit/@Model.actor.ActorID">
    <div class="inprow">
        <label class="inplabel">Actor First Name</label>
        <input type="text" value="@Model.actor.ActorFName" id="ActorFName" name="ActorFName" />
    </div>
    <div class="inprow">
        <div class="inplabel">Actor Last Name</div>
        <input type="text" value="@Model.actor.ActorLName" id="ActorLName" name="ActorLName" />
    </div>
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>
        

        

passionProject/Views/Actor/List.cshtml
@model IEnumerable<passionProject.Models.Actor>
@{
    ViewBag.Title = "List";
}

    <h2>Actor</h2>

<div class="recadd">
    @Html.ActionLink("Add a New Actor", "New","Actor")
</div>
<div class="reccontainer" style="overflow:hidden;">
    @foreach (var actor in Model)
    {

        <div class="rec">

            
            <div class="recbody">
                <label>@Html.ActionLink(actor.ActorFName, "Show/" + actor.ActorID)</label>
                
                <p>@actor.ActorLName</p>
                <P>@actor.Movie.Count()</P>
                <span class="del">
                    @Html.ActionLink("Delete","Delete/"+actor.ActorID)
                </span>
            </div>
            <div class="clearfix"></div>
        </div>

    }
</div>

passionProject/Views/Actor/Show.cshtml
@model passionProject.Models.Actor
@{
    ViewBag.Title = "Show";
}

<h2>@Model.ActorFName</h2>
<h2>@Model.ActorLName</h2>

<div>

 @Html.ActionLink("Edit","Edit/"+Model.ActorID)
</div>

<div class="del">

   @Html.ActionLink("Delete", "Delete/" + Model.ActorID)

</div>

<h3>List of Movies actor<h3>

    @foreach (var movie in Model.Movie)
    { 
        <span class="recitem">@Html.ActionLink(movie.MovieName,"Show/" + movie.MovieID,"Movie")</span>
    }

    @Html.ActionLink("Add a movie","New","Movie")




 <div>   
    <div class="clearfix"></div>
</div>

passionProject/Views/Actor/create.cshtml
@model passionProject.Models.ViewModels.ActorEdit
@{


    ViewBag.Title = "create";
}

<h2>Create Actor</h2>

<form method="POST" action="/Actor/Create">
    <div class="inputrow">
        <label class="inputlabel">Actor First Name</label>
        <input id="Actor" name="Actor_New" />
    </div>
    <div class="inputrow">
        <div class="inputlabel">Actor Last Name</div>
        <input id="ActorLName" name="ActorLName_New" />
    </div>
    <div class="inputrow">
        <input type="submit" value="Submit" />
    </div>
</form>